name: Calculate App Version

permissions:
    id-token: write
    contents: write

on:
    push:
        branches:
            - main
            - development
jobs:
    calculate-version:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0
              with:
                versionSpec: '5.x'
            - name: Calculate Version
              id: gitversion
              uses: gittools/actions/gitversion/execute@v0
            - name: Tag Repo
              run: |
                echo ${{ steps.gitversion.outputs.semVer }}
                git tag ${{ steps.gitversion.outputs.semVer }}
                git push origin ${{ steps.gitversion.outputs.semVer }}